# Generated by Django 5.1.3 on 2024-12-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pontuacao_delete_jogador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacao',
            name='pontuacao',
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='ganhador',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
